### ISSUE TITLE
ModuleNotFoundError: No module named 'leonardo'

### ISSUE THREAD

**Issue by Daeyangman** [leonardo-modules/leonardo-3d-viewer#1]
Hi , 

After i have installed 'leonardo-3d-viewer' by using pip3 in my virtual environment django web-framework  

And then I added 'leonardo' modules in models.py like as below 

from leonardo.module.web.models import Widget
from leonardo.module.web.widgets.forms import WidgetUpdateForm
from constance.forms import JsonField
from leonardo.module.media.fields import FileField

And then , i tried to migrate myproject. 

But , It seems like that have someting wrong.

How to solve it?

I want to show 3d model viewer in my project for user.  

Thank you

**Comment by michaelkuty** [comment]
Leonardo is standalone cms app which needs extra instalation steps, please proced the readme & doc for more informations.

and this module is designed only for leonardo cms applications
